project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!semester-transition-guide.md"

website:
  title: "DATASCI 101"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/danilofreire/datasci101
  repo-actions: [issue, source]
  repo-branch: gh-pages
  navbar:
    pinned: true
    tools:
      - icon: github
        href: https://github.com/danilofreire/datasci101
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures
      - href: assignments.qmd
        text: Assignments
      - href: LICENSE.html
        text: " "
  page-footer: 
    left: "The content of this site is licensed under the [MIT License](LICENSE.qmd)." 
    right: 
      - icon: github
        href: https://github.com/danilofreire/datasci101

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss, custom-dark.scss]
    css: styles.css
    mainfont: "Source Sans 3"
    monofont: "Inconsolata"
    highlight-style: github
    toc: true
